name: Test-Toot Weather
                             
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  toot-weather:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Python script
      run: |
        python emoji-weather-mastodon.py
      env:
        RUN_MODE: 'remote testing'
        OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        MASTO_DARK_WEATHER: ${{ secrets.MASTO_TEST_TOKEN }}
        MASTO_DARK_WIND: ${{ secrets.MASTO_TEST_TOKEN }}
        MASTO_LIGHT_WEATHER: ${{ secrets.MASTO_TEST_TOKEN }}
        MASTO_LIGHT_WIND: ${{ secrets.MASTO_TEST_TOKEN }}
        TARGET_TIMES_LOCAL: '20:00'
        TARGET_TIMES_HUMAN: 'Evening' 

      
