name: Tweet weather map

on:
  schedule:
  - cron:  '59 3,6,9,12 * * *'

env:
  OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }} 
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 
  TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }} 
  TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}

jobs:
  tweet-weather:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v2
    
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    
    - name: Install Python 2.7 dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run Python script
      run: python emoji-weather.py
